#!/usr/bin/env python3
import subprocess
VERSION = "0.1.0"
def run(cmd):
    try:
        return subprocess.check_output(cmd, shell = True, text = True).strip()
    except:
        return f"Error running: {cmd}"

def cpu_info():
    return run("lscpu | grep 'Model name'")

def memory_info():
    return run("free -h")

def disk_info():
    return run("df -h --total | grep total")

def ip_info():
    return run("ip -4 addr show | grep inet")

def uptime():
    return run("uptime -p")
    
if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()

    parser.add_argument("-c","--cpu", action="store_true")
    parser.add_argument("-m","--mem", action="store_true")
    parser.add_argument("-d","--disk", action="store_true")
    parser.add_argument("-i","--ip", action="store_true")
    parser.add_argument("-u","--uptime", action="store_true")
    parser.add_argument("-a","--all", action="store_true")

    args = parser.parse_args()

    # If no flags OR --all flag → show everything
    if args.all or not any(vars(args).values()):
        print(f"VERSION = {VERSION}")
        print("======== CPU INFO ================")
        print(cpu_info(), "\n")

        print("======== MEMORY INFO =============")
        print(memory_info(), "\n")

        print("======== DISK INFO ===============")
        print(disk_info(), "\n")

        print("======== IP INFO =================")
        print(ip_info(), "\n")

        print("======== UPTIME INFO =============")
        print(uptime(), "\n")
        exit()

    if args.cpu:
        print("======== CPU INFO ================")
        print(cpu_info(), "\n")

    if args.mem:
        print("======== MEMORY INFO =============")
        print(memory_info(), "\n")

    if args.disk:
        print("======== DISK INFO ===============")
        print(disk_info(), "\n")

    if args.ip:
        print("======== IP INFO =================")
        print(ip_info(), "\n")

    if args.uptime:
        print("======== UPTIME INFO =============")
        print(uptime(), "\n")
